### ISSUE TITLE
Выпуск №30 — 00:29 События

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#112]
[Аудио](https://soundcloud.com/web-standards/episode-30). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-30.md).

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by psywalker** [comment]
Беру на расшифровку!

**Comment by psywalker** [comment]
Беру на расшифровку!
