### ISSUE TITLE
Выпуск №22

### ISSUE THREAD

**Issue by thatsnotplasticine** [web-standards/podcast-old#14]
[Аудио](https://soundcloud.com/web-standards/episode-22). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-22.md).

- [ ] 00:13 События @thatsnotplasticine 
- [ ] 09:03 Samsung купила Joyent
- [ ] 13:39 Element Queries
- [ ] 17:30 React в Mail.Ru
- [ ] 25:31 Стандарты и семантика
- [ ] 45:51 Собеседования и новички
- [ ] 57:54 Как верстальщику стать замтехдира

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by firefoxic** [comment]
@thatsnotplasticine что-то есть набранное? Можно даже не целую тему запулреквестить.
