### ISSUE TITLE
Продакшен

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#147]
Я думал, что мне просто не нравится такое написание. Но залез в поисковики — и они все вместо этого варианта предлагают «продакшн». Нажимая _искать строго «продакшен»_ в выдаче получаю всё равно только варианты без _е_. Не уже ли весь интернет неправ?

**Comment by pepelsbey** [comment]
Иногда нужно идти против всех, если уверен в правоте ;) Ресепшн? Нет же, ресепшен.

**Comment by firefoxic** [comment]
В таком случае почему же у нас в yaspeller _б**э**ктики_ и _б**э**кенд_, но при том же корне _фолб**е**к_?
