### ISSUE TITLE
Firefox и WebM/WebP

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#152]
В Выпуске №26 есть фраза «Firefox вообще ничего не делает» в плане поддержки форматов WebP/WebM. Но это же не так — WebM без ограничений [поддерживается аж с 28й версии](http://caniuse.com/#search=webm). Про Edge да, инфа была озвучена верная — с WebM экспериментируют (уже поддерживает с 14 версии), и WebP не поддерживается.

Может про Firefox поправить? И если да, то с пометкой, мол примечание редактора, или без?

P.S. Сейчас вычитываю, скоро ПР будет с бургером в таблице. Могу в него же закинуть.

**Comment by pepelsbey** [comment]
Мне кажется, что такие правки массово делать бессмысленно — фактчекинг всего просто невозможен. Но если находится что-то явно некорректное, то можно делать что-то вроде:

> Волга впадает в Средиземное море! _([на самом деле нет](https://ru.wikipedia.org/wiki/%D0%92%D0%BE%D0%BB%D0%B3%D0%B0), прим. редактора)_

**Comment by firefoxic** [comment]
Я тоже к такому склонялся. Одно дело слова-паразиты выкидывать и фразы перестраивать в более читаемые, а другое дело вообще суть сказанного переделывать. Лучше в виде примечания :)
