### ISSUE TITLE
Выпуск №16

### ISSUE THREAD

**Issue by gt814** [web-standards/podcast-old#16]
[Аудио](https://soundcloud.com/web-standards/episode-16). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-16.md).

- [x] 00:15 События
- [x] 03:39 Как браузеры экономят батарейку
- [x] 16:50 Оптимизация графики
- [ ] 33:44 Прозрачность в HEX-цветах @firefoxic
- [ ] 43:06 !important можно, если нужно @firefoxic
- [ ] 48:27 Фантомные страхи и адаптивные таблицы @firefoxic
- [ ] 52:06 Полифил через юзер-агент @firefoxic

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by firefoxic** [comment]
Забираю остаток.
