### ISSUE TITLE
Форматирование тем подкаста в мобильных приложениях

### ISSUE THREAD

**Issue by targence** [web-standards/podcast-old#163]
Описание тем подкаста в мобильных приложениях (я пользуюсь Podcast Republic) отформатировано в одну строку.

Вот пример:
Источник http://feeds.soundcloud.com/users/soundcloud:users:202737209/sounds.rss

Именно с этим источником подкаст находится через поиск.

<img src="https://cloud.githubusercontent.com/assets/415928/24896179/5cedd2e4-1e9c-11e7-9b8d-f613f43dc96f.jpg"  width="50%">

<img src="https://cloud.githubusercontent.com/assets/415928/24897953/a1cb32d8-1ea3-11e7-80f9-8905c5264f32.jpg"  width="50%">

Как я понимаю проблема в самом soundcloud, он неверное форматирует тег `<description>`

Можете сравнить ваш фид и другого подкаста где темы отформатированы в виде списка
```
http://feeds.soundcloud.com/users/soundcloud:users:202737209/sounds.rss
http://feeds.feedburner.com/Radio-t
```
<img src="https://cloud.githubusercontent.com/assets/415928/24897940/941c8d58-1ea3-11e7-8065-28ae215d80b9.jpg"  width="50%">

Как возможное решение (если soundcloud устраивает как хостинг), то остается только брать rss с soundcloud и на лету его модифицировать, а затем этот модифицированный feed отдавать в  iTunes и др. агрегаторы подкастов.

Без этого description сейчас выглядит крайне не привлекательно.

**Comment by pepelsbey** [comment]
Спасибо за подобное описание проблемы. Вы, к сожалению, не первый. Действительно проблема в простом тексте — только его допускает SC и хостить подкаст там очень удобно. Нам бы очень пригодилась помощь с тем, чтобы генерировать RSS подкаста из наших описаний (благо они прямо здесь в удобном маркдауне) и как-то вмёрживать туда пути к файлам, поскольку хранить у нас их будет дороговато по трафику. А может и нет, но надо пробовать. В общем, бросим клич.

**Comment by targence** [comment]
Генерить  RSS  из описаний на  github будет довольно дорого, нужно где-то кешировать результаты парсинга гибхаба, синхронизировать и короче все закончится приложением на node.js со ста мегабайтами зависимостей и полугиговым образом докера, если повезет. :)

Было бы не очень изящно решать такую задачу так комплексно.

Если можно пожертвовать частью форматирования в виде заголовков разделов и др. мелочами, то можно просто в потоковом режиме переформатировать существующий  RSS от SC. В итоге это будет bash скрипт на пайпах и обвязкой на golang в виде сервера.  Докер образ будет ~20m 

Вот посмотрите RSS по этой ссылке —  http://t.targence.com/ws12
Форматировние происходит на лету. 
Имеет смысл потестировать в разных моб. приложениях.

<img src="https://cloud.githubusercontent.com/assets/415928/24953850/959c1558-1f85-11e7-9aad-60e58f2c1917.jpg"  width="50%">

Ссылки можно заворачивать в текст, это просто вопрос времени и вкуса.
В незавернутых ссылках есть преимущество, видно куда они ведут.

Если такой подход устаривает, то могу довести до использования в продакшене это наколеночное решение.

**Comment by pepelsbey** [comment]
Исправлено в #182
