### ISSUE TITLE
Сгенерировать XML-фид из описаний выпуска

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#182]
Хочется попробовать хостить RSS для подкаста самостоятельно: файлы уже лежат, осталось сгенерировать XML и попробовать. Есть две задачи:

1. Сделать из [списка MD-файлов](https://github.com/web-standards-ru/podcast/tree/master/episodes) большой XML-файл по всем правилам iTunes По сути, повозиться с Галпом или npm-скриптами какими-нибудь
2. Порисёрчить, что нужно сделать на сервере, чтобы правильно отдавать файлы (мультипарт какой-то) и потестировать как сейчас файлы отдаются: [96.mp3](https://web-standards.ru/podcast/episodes/96.mp3)

Зачем? Сейчас SoundCloud отдаёт плохой, плейн-текстовый RSS (см. #163) и многое приходится делать руками. Плюс платить им за подписку около 100 $ в год.

**Comment by pepelsbey** [comment]
Например, из такого файла:

```md
# Выпуск №0. 1 января 1970

Описание.

- Ольга Алексашенко
- Вадим Макеев
- Алексей Симоненко

Слушайте [в iTunes](https://itunes.apple.com/ru/podcast/veb-standarty/id1080500016) или [на SoundCloud](https://soundcloud.com/web-standards/episode-N), [обсуждайте в Слаке](http://slack.web-standards.ru/).

## Тема (00:00:00)

- [Статья](ссылка)
- [Статья](ссылка)
```

Хочется получить что-то такое:

```xml
<item>
  <title>Выпуск №N</title>
  <pubDate>Mon, 1 Jan 2017 00:00:00 +0000</pubDate>
  <itunes:duration>00:00:00</itunes:duration>
  <itunes:author>Ольга Алексашенко, Вадим Макеев, Алексей Симоненко</itunes:author>
  <itunes:explicit>no</itunes:explicit>
  <itunes:summary>Описание.</itunes:summary>
  <itunes:subtitle>Вертикальный ритм, Sass разрешил, переменные в пр…</itunes:subtitle>
  <description>
      <p>Описание.</p>
      <ul>
          <li>Ольга Алексашенко</li>
          <li>Вадим Макеев</li>
          <li>Алексей Симоненко</li>
      </ul>
      <p>Слушайте <a href="https://itunes.apple.com/ru/podcast/veb-standarty/id1080500016">в iTunes</a> или <a href="https://soundcloud.com/web-standards/episode-N">на SoundCloud</a>, <a href="http://slack.web-standards.ru/">обсуждайте в Слаке</a>.</p>
      <h2>Тема (00:00:00)</h2>
      <ul>
          <li><a href="ссылка">Статья</a></li>
          <li><a href="ссылка">Статья</a></li>
      </ul>
  </description>
  <enclosure type="audio/x-m4a" url="https://web-standards.ru/podcast/episodes/N.mp3" length="000000000"/>
  <itunes:image href="https://web-standards.ru/podcast/cover.jpg"/>
</item>
```

**Comment by pepelsbey** [comment]
Это включает:

- Конвертацию из MD в HTML
- Генерацию даты из заголовка
- Генерацию длительности в секундах: `<itunes:duration>`
- Генерацию размера в байтах `<enclosure length="000000000"/>`

Формат MD можно менять и дополнять.

**Comment by DariusNorv** [comment]
cover для itunes может тоже менять для каждого выпуска? ну например класть рядом с mp3 и забирать по урлу `<itunes:image href="https://web-standards.ru/podcast/episodes/cover-N.mp3"/>`

**Comment by pepelsbey** [comment]
У нас пока нет уникальных обложек для каждого выпуска, но наверное можно придумать.

**Comment by vldmkrsh** [comment]
Можно смотреть есть ли обложка для этого выпуска, или брать по умолчанию. Я бы вот точно отметил другой обложкой выпуск 85.

**Comment by DariusNorv** [comment]
Написал первую версию парсера (пока сыровоата), появились некоторые вопросы по реализации.
Первую версию пытался загрузить в отдельную ветку в этот репозиторий но судя по всему нет прав.
![image](https://user-images.githubusercontent.com/1824547/33740128-9d2569fe-dbb0-11e7-8788-265e5173e911.png)

Написал @pepelsbey в слак, если что пишите мне https://web-standards.slack.com/messages/@U7C802E9X

**Comment by pepelsbey** [comment]
@DariusNorv, так форкайте и предлагайте пулреквест :) Если поймём, что оно и дело пойдёт, то дадим права для пуша. Но сначала нужно посмотреть, что выходит.

**Comment by DariusNorv** [comment]
Разумеется, так и поступим 👍

**Comment by DariusNorv** [comment]
@pepelsbey Гляньте в PR обновил согласно пожеланиям. Если все ок можно в слаке дообсудить детали, а я на досуге поизучаю что на сервере настроить надо. ✌️

**Comment by pepelsbey** [comment]
На этой неделе попробую локально и может сразу смёржу, чтобы можно было настроить автоматическую публикацию фида на сайт.

**Comment by DariusNorv** [comment]
Мержить рано :) нужно наполнить инфой обертку XML-ки, относительно вашего канала.
Можно просто собрать и запустить - если на выходе XML получится годная то ОК

**Comment by pepelsbey** [comment]
Спасибо всем!
