### ISSUE TITLE
Завести сборку фида

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#185]
Генератор фида готов, думаю завстра смёржу #184. Надо его теперь деплоить при сборке. Тревис уже тестирует спеллером, так что нужно ему сказать, чтобы он запускал кроме `npm test` ещё и `node feed`. А получившийся файл `index.xml` в корне репозитория нужно синкать в папку `/podcast/feed/`.

@h4 сможешь помочь на неделе?

**Comment by hrbchv** [comment]
Вадим, вы меня с Михаилом спутали.

пн, 12 февр. 2018 г. в 17:26, Vadim Makeev <notifications@github.com>:

**Comment by h4** [comment]
@pepelsbey свистни, как смёржишь.

**Comment by pepelsbey** [comment]
@h4 фьюить
