### ISSUE TITLE
Лучше <p> вместо <h1> для описания в фиде

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#195]
Сейчас получается так:
```html
<h1>1 февраля 2016: DESC</h1>
<ul>
    <li>Ольга Алексашенко</li>
    <li>Вадим Макеев</li>
    <li>Алексей Симоненко</li>
</ul>
```
Я понимаю, откуда берётся `<h1>`, но именно в фид туда просится скорее `<p>`.

**Comment by DariusNorv** [comment]
Пришлось закостылить оригинальный пакет всегда генерит с заголовком.

**Comment by pepelsbey** [comment]
Исправлено в #197
