### ISSUE TITLE
Поправка ко времени

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#198]
Когда я запускаю сборку локально то поправка +3

```xml
<pubDate>Mon, 26 Feb 2018 12:00:00 +0300</pubDate>
```

Когда это делает Тревис, то +0

```xml
<pubDate>Mon, 26 Feb 2018 12:00:00 +0000</pubDate>
```

Может её как-то выровнять под те самые 9 утра или не париться вообще со временем?

**Comment by pepelsbey** [comment]
Единственный простой способ протестировать был смёржить :)

Локально:
```
<pubDate>Mon, 1 Feb 2016 12:00:00 +0300</pubDate>
```
На Тревисе:
```
<pubDate>Mon, 1 Feb 2016 03:00:00 +0300</pubDate>
```

То есть выпуск выходит в 6 утра по Москве (3 + 3). Такой был план?

**Comment by DariusNorv** [comment]
Неа.... не такой =( План был чтобы на Трэвисе было корректное Московское время.
Ладно я разберусь.

**Comment by DariusNorv** [comment]
Это я подправил, должно теперь быть нормально. Не пушнул еще т.к. с #200 есть проблемы.

**Comment by h4** [comment]
Мне кажется, что правильнее выставить таймозону на тревисе, а не хардкодить в библиотеке.

**Comment by pepelsbey** [comment]
Сейчас фид выдаёт дату в будущем, на что ругается [валидатор](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fweb-standards.ru%2Fpodcast%2Ffeed%2F):
```
Implausible date: Mon, 5 Nov 2018 12:00:00 +0300
```
Подкаст обычно выходит в 9:00 утра по GMT+3, вот бы нам как-то эту дату зафиксировать.
