### ISSUE TITLE
Неправильная длительность в фиде

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#200]
Выпуск №109 по MP3-файлу 01:19:30, а в фиде написано:
```xml
<itunes:duration>01:17:04</itunes:duration>
```
Заметил и пошёл проверять потому, что iTunes Connect показывает ошибку, это про 108-й
![image](https://user-images.githubusercontent.com/105274/36692608-9e51d186-1b49-11e8-85bc-1c09c1aee507.png)

**Comment by DariusNorv** [comment]
Проблема со всеми выпусками, как оказалось. Погрешность между расчетами в ~63 секунды.
Либо проблема в формуле расчета, либо в битрейте. Я считаю что битрейт 64 кбит/сек. @pepelsbey можно уточнить точный битрейт и не помешало бы уточнить софт, которым ужимаете.

**Comment by pepelsbey** [comment]
Сжимаю с помощью [Forecast](https://overcast.fm/forecast), у него внутри лежит `libmp3lame.dylib`, то есть обычный LAME. Битрейт 64:

![image](https://user-images.githubusercontent.com/105274/36785183-0d64dd58-1c93-11e8-94ad-368a04dc556b.png)

Вот что `ffmpeg` говорит про `109.mp3`

```
Input #0, mp3, from '/Users/pepelsbey/Documents/Веб-стандарты/Подкаст/MP3/109.mp3':
  Metadata:
    album           : Веб-стандарты
    artist          : Веб-стандарты
    title           : Выпуск №109
    comment         : 26 февраля 2018: Где нас слушать, события и завтраки, старые и новые движки, npm догнал yarn, гриды на пустом месте, кастомные или системные шрифты, �
    lyrics-eng      : 26 февраля 2018: Где нас слушать, события и завтраки, старые и новые движки, npm догнал yarn, гриды на пустом месте, кастомные или системные шрифты, �
    TLEN            : 4770000
    encoded_by      : Forecast
    date            : 2018
  Duration: 01:19:30.06, start: 0.000000, bitrate: 64 kb/s
    Chapter #0:0: start 0.000000, end 172.869000
    Metadata:
      title           : Интро
    Chapter #0:1: start 172.869000, end 421.592000
    Metadata:
      title           : Где нас слушать
    Chapter #0:2: start 421.592000, end 1091.560000
    Metadata:
      title           : События и завтраки
    Chapter #0:3: start 1091.560000, end 1788.692000
    Metadata:
      title           : Старые и новые движки
    Chapter #0:4: start 1788.692000, end 2491.919000
    Metadata:
      title           : Новый npm догнал yarn
    Chapter #0:5: start 2491.919000, end 2753.800000
    Metadata:
      title           : Гриды на пустом месте
    Chapter #0:6: start 2753.800000, end 3224.120000
    Metadata:
      title           : Кастомные или системные шрифты
    Chapter #0:7: start 3224.120000, end 4049.500000
    Metadata:
      title           : Устаревшие рекомендации
    Chapter #0:8: start 4049.500000, end 4770.000000
    Metadata:
      title           : Опасные алиасы в консоли
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 64 kb/s
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1400x1400 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

**Comment by DariusNorv** [comment]
Окей, буду разбираться что не так в моих расчетах. Постарась до воскресенья решить эту проблему, в крайнем случае выложу костыль, с ним погрешность 1 секунда.
Для того чтобы тестировать в iTunes Connect насколько я понимаю нужен инвайт? Если это возможно то я бы мог тоже потестить, мой appleId `norv.darius@gmail.com`

**Comment by pepelsbey** [comment]
Кажется статистику никак не пошарить. А тестировать можно просто: когда длительность в фиде сравняется с файлами — значит всё хорошо :)
