### ISSUE TITLE
Хук с проверкой MP3 мешает коммитить

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#202]
Мои попытки закоммитить `README.md`, имея черновик `110.md`, но не имея `110.mp3` на сервере, приводят к ошибке и это как-то неправильно и неудобно. Может прицепить хук на какое-то другое действие (пуш?) или проверять не все файлы.

```
Commit failed - exit code 1 received, with output: '> @ validate:audio /Users/pepelsbey/Documents/Веб-стандарты/Подкаст/Расшифровки
> node feed/validation/audioExists

File https://web-standards.ru/podcast/episodes/110.mp3 not found on server
```

**Comment by DariusNorv** [comment]
Нет разницы на пуш или на коммит вешать хук кмк. Можно удалить файл с хуком (или всю директорию `.githooks`)
Ну или проверять все кроме последнего... ну только это странно все
Идея то была в том чтобы перед коммитом проверить все ли ок, может более правильно заранее файл на сервер залить?

**Comment by pepelsbey** [comment]
Процесс такой, что черновик появляется раньше, чем готов файл на сервере. Я бы перевесил на пуш, ведь только пуш заводит Тревис и на что-то влияет, а локальный коммит ничего такого не делает.

**Comment by DariusNorv** [comment]
Сделал на пуш)

**Comment by pepelsbey** [comment]
А мне весь пулреквест для этого мёржить? Я думал, там не готово ещё, а коммитить быстрее и ненапряжнее хотелось бы :) Перенесёшь отдельно? Дать хоть коммитом, без пулреквеста.

**Comment by DariusNorv** [comment]
Я не подумал об этом) Счерипикаю в мастер как доберусь до дома

**Comment by DariusNorv** [comment]
@pepelsbey счерипикал в мастер) можно коммитить)
