### ISSUE TITLE
Неправильное отображение описания в google podcast  

### ISSUE THREAD

**Issue by plotkopavlo** [web-standards/podcast-old#207]
1.  Заголовки прилипают к предыдущему абзацу. Касается всех выпусков
2. Он режет описание (Касается всех, но сильно начал резать с 11)
Скриншоты (android 6): 
![google-podsact-1](https://user-images.githubusercontent.com/24277571/43119472-369176d8-8f1f-11e8-9507-c5e808fbb5be.jpg)
![google-podcast-10](https://user-images.githubusercontent.com/24277571/43119470-365e0f50-8f1f-11e8-85c5-becd33f36816.jpg)
![google-podcast-11](https://user-images.githubusercontent.com/24277571/43119471-367736f6-8f1f-11e8-8dd1-2e3f440e9664.jpg)
![google-podcast-120](https://user-images.githubusercontent.com/24277571/43119474-36ab8668-8f1f-11e8-8b0f-a891e650afd9.jpg)

**Comment by pepelsbey** [comment]
Не уверен, что мы тут можем сделать. Разметка вот такая:

```html
<ul>
  <li>Ольга Алексашенко</li>
  <li>Вадим Макеев</li>
  <li>Алексей Симоненко</li>
</ul>
<h2>Содержание</h2>
```

То есть прилипать не должно. Можно конечно попробовать `<h2>` на что-нибудь заменить и проверить. Попробую. А вот насчёт обрезания описания точно вряд ли — похоже, что там какой-то жёсткий лимит. Если описание длинное, то ничего не поделать.

**Comment by sierikov** [comment]
@plotkopavlo пожалуйста обновите версию Google Podcast до `v.1.0.0.200631462`. На этой версии разметка отображается коректно (смотрите скриншоты). Если проблема решена, пожалуйста закройте Pull-Request.

Выпуск 120:
![120](https://user-images.githubusercontent.com/22551739/60441812-15c6a980-9c18-11e9-9afb-2a71faca53c3.jpg)

Выпуск 110:
![110](https://user-images.githubusercontent.com/22551739/60441813-15c6a980-9c18-11e9-9d99-90626fa00853.jpg)

**Comment by pepelsbey** [comment]
@ArtemSer спасибо за расследование! Ждём ответа @plotkopavlo :)
