### ISSUE TITLE
Поддержать анлоязычный формат даты

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#209]
Сейчас парсер кладёт в `<pubdate>` начало описания:

```
17 сентября 2018: 10 лет Chrome, кому нужен URL, что такое каскад…
```

Но есть два выпуска (85, 139 и другие в будущем), где дату хочется давать по-английски:

```
September 25th, 2018: Four interviews with CSS-Minsk-JS speakers…
```

Формат `September 25th, 2018`, уж не знаю как его записать абстрактно. Дата без ведущего нуля и с постфиксом числительного.

**Comment by pepelsbey** [comment]
@DariusNorv кажется, что правка должна быть простой. Будет время сделать фикс? :)

**Comment by DariusNorv** [comment]
@pepelsbey я правильно понял будут некоторые выпуски где дата должна быть на английском?

**Comment by pepelsbey** [comment]
Именно, то есть нужно уметь из двух форматов делать нужный для фида.

**Comment by DariusNorv** [comment]
Можно сделать. У меня предложение именовать файлы с суффиксом `en` для английского языка, например `episode-02.en.md` чтобы парсером отделять английские и русские версии

**Comment by pepelsbey** [comment]
А может лучше регулярку сделать универстальную, которая может находить оба формата? Хочется, чтобы страдали машины :)

**Comment by DariusNorv** [comment]
Да я в принципе тоже за то чтоб машины страдали, Пока то что я вижу можно детектить язык по заголовку. Годится?

**Comment by pepelsbey** [comment]
А нельзя просто чекать дату в начале описания одной регуляркой, потом другой и делать вывод? Они очень простые должны быть.

**Comment by DariusNorv** [comment]
Не очень понимаю как я буду чекать дату регуляркой. Я вижу что выпуски английские имеют английский заголовок Episode а русские по русски Выпуск - кмк регулярно сделать можно по заголовку

**Comment by pepelsbey** [comment]
Ну ок, тебе виднее за что цепляться, благо там очень формализовано всё :)

**Comment by DariusNorv** [comment]
Закрываем?

**Comment by pepelsbey** [comment]
Да! Спасибо :)

**Comment by pepelsbey** [comment]
Сейчас в фиде всё плохо (
```
<title>Episode #85</title>
<pubDate>Invalid date</pubDate>
<description><![CDATA[<p>September 14th, 2017
…
<title>Episode #139</title>
<pubDate>Invalid date</pubDate>
<description><![CDATA[<p>September 25th, 2018
```

**Comment by pepelsbey** [comment]
А если вернуть дату в кириллическую, что всё в порядке:
```
<title>Episode #85</title>
<pubDate>Thu, 14 Sep 2017 12:00:00 +0300</pubDate>
<description><![CDATA[<p>14 сентября 2017
```

**Comment by pepelsbey** [comment]
Может я неправильно объяснил: обе даты `14 сентября 2017` и `September 14th, 2017` должны давать `Thu, 14 Sep 2017 12:00:00 +0300` в `<pubDate>`. Автоматически (по регулярке) или по слову «episode» они это будут делать — неважно. Главное, чтобы могли.

**Comment by DariusNorv** [comment]
Упс, я кажется упустил где-то еще конвертацию. Поправим

**Comment by DariusNorv** [comment]
Я поправил @pepelsbey проверь плиз.
Если что-то непонятно давай в ПР обсудим, лучше сто раз проверить чтобы не повторилось
