### ISSUE TITLE
Поддержать новый формат заголовков

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#214]
Хочется, чтобы описательный заголовок тоже парсился:

```md
# 167. Редакторы, фреймворки, образование и Илья Климов из GitLab
```

Но сейчас он выдаёт `# 167`

**Comment by pepelsbey** [comment]
Есть план перевести в новый формат все заголовки — будущие и прошлые.

**Comment by DariusNorv** [comment]
Сори я упустил из виду пожелание :( @pepelsbey если вопрос актуален было бы неплохо чтобы в отдельную ветку запушил пример маркдаун файла с заголовком в новом формате.
Нужно будет сделать режим совместимости чтобы парсер сам понимал какой формат заголовков и как парсить или будет единовременный переход?

**Comment by pepelsbey** [comment]
Привет :) Лучше конечно сделать режим совместимости: старая русская и английская и новая универсальная с точкой после цифры. Но если муторно, то можно только новую и в отельную ветку, куда я за недельку допушу все названия в новом формате.

**Comment by DariusNorv** [comment]
Режим совместимости сделать можно, но я тут не столько за муторность сколько за единообразие :) По мне лучше тогда сразу все переводить.
Предлагаю так. Запуш в отдельную ветку сначала один пример и я в ней же доделаю парсер. Потом все выложим разом

**Comment by pepelsbey** [comment]
Ок!

**Comment by pepelsbey** [comment]
Готово: в новой ветке new-title [поменял формат](https://github.com/web-standards-ru/podcast/commit/b14d7c021544b5b985c38fced54e68e7efdf5d3d) последних 12 выпусков.

**Comment by pepelsbey** [comment]
FYI, [я начал с нуля](https://github.com/web-standards-ru/podcast.11ty) и переделываю генерацию фида на движке [Eleventy](https://www.11ty.io). В файлах появилось больше меты и работы с MP3 уже не будет.
