### ISSUE TITLE
Обратный порядок выпусков в Яндекс.Музыка

### ISSUE THREAD

**Issue by vitasar** [web-standards/podcast-old#215]
Рассмотреть возможность поменять порядок выпусков в Яндекс.Музыка на обратный.
На данный момент записи расположены от конца к началу. Это приводит к тому, что нельзя слушать записи в прямом порядке и приходится переключать записи вручную.

![Screenshot_20190711-205358](https://user-images.githubusercontent.com/6786066/61073411-0b798c00-a41e-11e9-95d8-0c31b0da7601.jpg)

**Comment by pepelsbey** [comment]
Это новостной подкаст. Если первым, что будет встречать публику, будет Выпуск №1 с новостями февраля 2016 года, то это будет гораздо хуже, чем неудобство переключения треков. Тут две сложности: подкасты — это экспериментальная возможность Яндекс.Музыки, поэтому интерфейс не совсем готов. Вторая в том, что наши выпуски по часу и больше раз в неделю очень редко слушают один за другим.
