### ISSUE TITLE
Нумерация эпизодов

### ISSUE THREAD

**Issue by fetis** [web-standards/podcast-old#31]
Сейчас
`episode-2.md`

И уже сейчас есть проблемы с сортировкой.
Предлагаю вести нумерацию с лидирующими нулями `episode-002.md`

**Comment by pepelsbey** [comment]
Вряд ли этот репозиторий будет главным интерфейсом для доступа к расшифровкам, мы будем давать на них ссылки, автоматизируем публикацию на сайте. Всё лучше, чем приделывать ведущие нули, которые мешают считывать номер выпуска. Плюс сейчас URL на SoundCloud совпадает с именами файлов.

**Comment by firefoxic** [comment]
В атоме нормальная сортировка. Разнобой видел в выпусках только в списке файлов в веб-морде гитхаба. Но я там файлы практически никогда не выбираю, поэтому не видел особой в этом проблемы. Я вообще хотел как-то раз предложить по датам именовать. Но это уже слишком наверно. Да и раз уж если с SC удобнее так как сейчас…
Вот каждую главу всех выпусков сделать ссылкой на соответствующий момент на SC — это та ещё задачка будет, наверное.

**Comment by pepelsbey** [comment]
@fetis, всё-таки сделал так — мешало работать с файлами. Спасибо!
