### ISSUE TITLE
Ишьи как таски.

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#40]
Во второй (и надеюсь не последней) редакции предложенного мной [контрибьютинга](https://github.com/web-standards-ru/podcast/pull/21) есть одно правило оформления PR для не большой автоматизации. И [последний свой Pull Request](https://github.com/web-standards-ru/podcast/pull/38) я оформлял в соответствии с ним. И там ничего сложного. Но  захотелось больше космоса.

Вот мои предложения (начиная с п.3 — взято из [контриба bem_components](https://github.com/bem/bem-components/blob/v3/CONTRIBUTING.ru.md)):
1. Создать (заранее) ишьи для каждого не набранного из прежних выпусков с названием `«Выпуск №__»`
2. При появлении нового выпуска создавать (сразу же) ишьи для каждой темы с названием `«Выпуск №__ — [таймкод] Название темы»`
3. Ветку в собственном форке называть как уже сейчас описано в контрибе: `issues/<номер_ишьи_выбранного_выпуска_или_темы>`
4. ПР называть идентично названию ишьи.
5. В тело сообщения ПР вкючить фразу, [закрывающую при мерже ишью](https://github.com/blog/1506-closing-issues-via-pull-requests)

Какой профит:
1. Наборщики будут сразу видеть целым списком (как таск-лист) именно то, что нужно набирать.
2. Зайдя в выбранную ишью отметиться можно даже одним словом («Беру», например). Или же узнать, что оно уже взято (возможно как-то метками взятость отмечать)
3. Мерж ПРа автоматом закрывает эту ишью благодаря метке с ключевым словом ([их несколько](https://help.github.com/articles/closing-issues-via-commit-messages/), можно выбрать любое) и номером ишьи
4. Именование ветки в форке с включением номера ишьи позволяет не запутаться в номерах (во время создания ПР название ветки видно, из него номер и берём для закрывающей фразы в тело сообщения)
5. Вадиму не приходится закрывать мёртвые не нужные ишьи, только Мерж ПР, фокус только на набранный контент.
6. В новых выпусках, нет никаких «Отсюда, и где-то вон до тудова». Всё чётко: одна тема со своим таймкодом — одна ишья. Запутаться и потерять какой-то кусок можно только с будуна.

**Comment by firefoxic** [comment]
Объяснение наверно путанное, но даже в контриб добавлять ничего не понадобится к тому, что сейчас в нём есть (и даже одну строчку точно выкинуть), просто ишьи создать все нужные.

**Comment by pepelsbey** [comment]
Мне нравится идея создавать ишьи для каждого выпуска, который нужно создавать. А внутри уже можно договариваться о тайминге и, при необходимости, создавать доп. ишьи.

**Comment by pepelsbey** [comment]
Без этого непонятно, что именно можно взять. Нет списка задач.

**Comment by firefoxic** [comment]
Почему не понятно? Наоборот, стоит только в ишьи зайти — сразу картина вся видна будет.

Для примера, допустим это дело уже принято. Для выпусков до 24-го — 1 ишья для 1 выпуска, с 24-го — 1 ишья на 1 тему. Опубликован новый выпуск. Я прослушал, и мне захотелось из 5 тем набрать 3-ю. Захожу в ишьи (и там их много, потому что старые выпуски пока ещё висят). Вижу с номером нового выпуска 3-ю тему (по таймингу), захожу в неё, а там уже чей-то коммент «Забираю». Опоздал. Ладно, беру другую, но их остаётся только 3, а не 4. Почему? Да потому что одну из тем (допустим 2-ю) не просто взяли, а уже отправили ПР, и этот ПР уже смержен, а ишья с ним связанная автоматом закрылась. Потом 3-я тема смержится+закроется. Мной выбранная и отправленная (допустим 5-я) тема тоже смержится+закроется. И следующему захотевшему помочь видны только две оставшиеся ишьи про новый выпуск: 1 и 4 темы. Бери и набирай (если не помечены ещё).

Сам список Issues — чем не список задач?

Сейчас без этого, чтобы понять какой из старых ещё не набран — это мне надо свой форк с апстримом синхронизировать, спуллить его на локалку, протыкать в редакторе старые выпуски и увидеть, какие пустые, потом идти в ишьи и искать, нет ли мной выбранного среди них. В веб-морде ещё неудобнее искать по файлам.

С новыми вообще всё неудобно. Вот прямо сейчас мне (а тем более кому-то со стороны) понять, что же в 26-ом выпуске ещё не набрано — я честно не представляю как. Даже и держать открытыми 2 вкладки: с открытыми ишьями и закрытыми. Это ж надо сообразить, что значат все эти «отсюда и до забора» и как-то их в голове смержить в общую картину. Как по мне, так очень легко, что-то упустить. Единственный способ — зрительно просканировать файл, все ли тайминги в нём есть, и под каждым ли из них есть текст. Я например, даже не уверен сейчас, набран ли весь 25-й выпуск. А может не весь? А может целая тема пропущена? А может не целая, а кто-то набрал «до забора» а дальше не набрано. И это хорошо, что пока ещё только 3 выпуска так раздербанивались. А если уже 20+ выпусков в таком режиме набирались? Пойди просканируй каждый. И всё это будет снежным комом.

И это я ещё вроде как пытаюсь быть в теме. А если кому-то со стороны, впервые захотевшему помочь с этим? В предложенном варианте на это дело (одна не набранная тема в 25-ом выпуске) висела бы ишья, никем не помеченная комментом «Забираю». Человек пишет «Забираю эту тему». И далее по контрибьютингу всё делает, и закрывает полностью 25й выпуск. Никаких лишних поисков, только полезная работа.

**Comment by firefoxic** [comment]
Кстати, в [вафле](https://waffle.io/web-standards-ru/podcast) эта картина с ишьями была бы ещё более наглядной. А сейчас и вафля практически бесполезна для выбора чего набирать.

**Comment by pepelsbey** [comment]
> Почему не понятно?

Я имел в виду, что _без этого_ не понятно, а с этим будет понятно.

**Comment by firefoxic** [comment]
Видимо не так понял я.
Если бы ещё в вафле как-то своевременно перемещать автоматом в Ready (хотя это можно сразу даже) и In Progress (а вот это сложно, надо при взятии в набор: автоматическое я не нашёл как делать, а вручную — это ж надо следить за этим делом). Вот было вообще круто.

**Comment by firefoxic** [comment]
@pepelsbey, думаю в контрибе стоит указать про слаку, что всё обсуждение тут ведём.

**Comment by firefoxic** [comment]
Я тут подумал. Ишьи-то вроде кто угодно может создавать, не обязательно оунеру.
Вот только следить за их состоянием кто-то должен и вовремя закрывать, если автозакрывашку не вставили в ПР. Например, про Safari и MathML до сих пор ишья висит.

**Comment by pepelsbey** [comment]
@firefoxic я иногда заглядываю и чищу. Могу автивистов также добавить в организацию, чтобы вы могли приглядывать сами :)

**Comment by firefoxic** [comment]
Это конечно можно, но вопрос в том, когда состоится переход на работу по контрибу. А для этого наверно надо, чтобы у тебя появилось время на правку этого контриба (вроде собирался это сделать).

**Comment by firefoxic** [comment]
Я бы прямо сейчас уже к каждой теме 27го создал бы ишью _пока не началось_. Чтоб просто разбирали уже созданные.

**Comment by pepelsbey** [comment]
Решено, будем работать по схеме:
1. На каждую тему нового выпуска заводится таск и ставится лейбл «расшифровка»
2. Желающий расшифровать тему — назначает её на себя
3. Как только расшифровка закончена — таск закрывается.

Внутри таска можно расставлять чекбоксы с этапами, при желании. Изначальные таски по выпускам может создавать любой участник редакции. Также стать участником организации нужно, чтобы назначать на себя таски. Так что позвал @psywalker, @firefoxic и @Jazzis18.

```
Выпуск №27 — 00:26 События
Выпуск №27 — 04:57 Инлайновое видео в iOS
Выпуск №27 — 08:09 ChakraCore на Mac и Linux
Выпуск №27 — 25:12 Модальные окна
Выпуск №27 — 32:43 Сложные таблицы
Выпуск №27 — 37:13 Формы и доступность
Выпуск №27 — 44:04 Чехарда с цветовыми функциями
```

**Comment by pepelsbey** [comment]
@firefoxic @psywalker @Jazzis18, ребята, не пугайтесь, я снова немного помудрил с правами доступа. Сделал умнее в этот раз: вместо того, чтобы давать вам админский доступ ко всему на свете, я просто добавил вас внешними коллабораторами с нужными правами (write) к нужным репозиториям. Если не будет хватать — дам «admin». Просто у нас есть формальная редакция «Веб-стандартов» с отдельным чатом и т.п. — это совсем другая история.

**Comment by firefoxic** [comment]
Если это означает, что прекратятся письма про непонятные ишьи и пээры, то я рад)

**Comment by pepelsbey** [comment]
Именно!
