### ISSUE TITLE
Выпуск №26 — 18:12 Будущее WebP и WebM

### ISSUE THREAD

**Issue by Jazzis18** [web-standards/podcast-old#42]
[Аудио](https://soundcloud.com/web-standards/episode-26). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-26.md).

**Comment by pepelsbey** [comment]
Позвал вас в организацию, чтобы можно было назначать таски на вас. Самоназначьтесь :)

**Comment by firefoxic** [comment]
@Jazzis18, а тут только вычитка осталась? Может помочь с вычиткой?

**Comment by Jazzis18** [comment]
@firefoxic, тут ПР надо запилить кажись. Я к нему не возвращался. Надо поглядеть, как он поживает.

**Comment by firefoxic** [comment]
Надо бы. С этим ПР и с моим последним будет полный набор. А после полной вычитки Игорем — можно смело ставить бургер в табличке)
