### ISSUE TITLE
Выпуск №27 — 00:26 События, 04:57 Инлайновое видео в iOS

### ISSUE THREAD

**Issue by psywalker** [web-standards/podcast-old#44]
[Аудио](https://soundcloud.com/web-standards/episode-27). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-27.md).

Беру на расшифровку две первые темы (от 00:00 до 08:09): 
"00:26 События" 
"04:57 Инлайновое видео в iOS"

**Comment by pepelsbey** [comment]
@psywalker поставь на себя #45 и #46, этот закрываю
