### ISSUE TITLE
Выпуск №27 — 04:57 Инлайновое видео в iOS

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#46]
[Аудио](https://soundcloud.com/web-standards/episode-27). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-27.md).

**Comment by pepelsbey** [comment]
Занято @psywalker, как только он подтвердит приглашение — поставлю официально (или он сам).

**Comment by psywalker** [comment]
Подтверждаю)
