### ISSUE TITLE
Выпуск №1

### ISSUE THREAD

**Issue by imperialowl** [web-standards/podcast-old#5]
[Аудио](https://soundcloud.com/web-standards/episode-01). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/pilot-1.md).

Взялся за расшифровку imperialowl (@ultraowl - slack)

- [x] 00:45 Новинки браузеров
- [x] 07:42 PhantomJS 2.1
- [x] 10:16 Переменные в CSS
- [x] 19:43 Sass с PostCSS
- [x] 24:37 Загрузка шрифтов
- [x] 32:36 Спрайты
- [x] 36:25 Адаптивные картинки
- [x] 38:01 HTTPS
- [x] 48:12 Парадоксы HTML и CSS
- [x] 52:05 Коты JS-фреймворки

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by firefoxic** [comment]
Забираю оставшуюся половину.
