### ISSUE TITLE
Выпуск №27 — 37:13 Формы и доступность

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#50]
[Аудио](https://soundcloud.com/web-standards/episode-27). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-27.md).

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by firefoxic** [comment]
Беру
