### ISSUE TITLE
Выпуск №26 — 29:46 Зачем HyperTerm?

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#69]
[Аудио](https://soundcloud.com/web-standards/episode-26). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-26.md).

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by Jazzis18** [comment]
Возможно я возьму, т.к. когда-то начинал расшифровывать, но не отметился. Закрою свои обе таски, и если никто не возьмет, то возьму.

**Comment by firefoxic** [comment]
@Jazzis18 не берёшь этот кусок?

**Comment by Jazzis18** [comment]
@firefoxic Нет.

**Comment by firefoxic** [comment]
Возьму тогда, надо добить уже его, чтоб бургер в таблице поставили :)
