### ISSUE TITLE
Таблица в README.md

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#78]
Классная идея. Напрашивалось что-то взамен простого ряда цифр.

Но я покритикую.
1. не понятно зачем целая строка для знака «№», вообще он тут не особо нужен, и так понятно, что это порядковые номера;
2. **N** — не понятно, что имеется в виду жирность шрифта, при том что заранее знал про выделение жирным набранных выпусков из описания коммитов, мне было бы понятнее в самой таблице что-нибудь вроде [25<sup>р</sup>](episodes/episode-25.md), ну или просто эту «**N**» заменить на «**Выделенное жирным**»;
3. Мне как-то всегда не хватало в этом списке дат выпуска, её можно сделать в виде тайтла к ссылке, например, ибо таблицу на основе дат наверно будет очень сложно сконструировать.

**Comment by pepelsbey** [comment]
1. Целая строка для № потому, что Markdown не узнаёт таблицу без заголовка. Может я что-то не так понял, буду пробовать ещё.
2. Выделение полужирным и правда будет понятнее, поправлю.
3. Подумаю куда вставить даты, может вообще календарь сделаю.

**Comment by firefoxic** [comment]
Да, тоже не нашёл таблиц без заголовка :(

**Comment by pepelsbey** [comment]
Сделал заметнее

![image](https://cloud.githubusercontent.com/assets/105274/17465683/6ad87d7a-5d07-11e6-912f-5eda9b5b1593.png)

**Comment by firefoxic** [comment]
Бургер классно смотрится :) к жирному надо было ещё и присматриваться.
И сноска теперь понятна более чем.
Считаю, что больше нечего менять (даты — это вообще отдельная история).
