### ISSUE TITLE
Выпуск №28 — 40:24 CSS-демки

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#87]
[Аудио](https://soundcloud.com/web-standards/episode-28). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-28.md).

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by Jazzis18** [comment]
Беру.

**Comment by Jazzis18** [comment]
Выхи пришли, за выхи наберу взятые.
