### ISSUE TITLE
Выпуск №17

### ISSUE THREAD

**Issue by cyber-snail** [web-standards/podcast-old#9]
[Аудио](https://soundcloud.com/web-standards/episode-17). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-17.md).

- [x] 00:13 События
- [x] 04:01 Семантика и БЭМ
- [x] 29:40 CSS для новичков
- [x] 32:09 Контроль версий и клиенты
- [x] 45:51 JS-модули в Edge!
- [x] 51:42 Google I/O

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by firefoxic** [comment]
@pulmo что-то есть набранное? Можно даже не целую тему запулреквестить.

**Comment by cyber-snail** [comment]
Прошу прощения, что так долго. Немного осталось, на праздниках все разом отправлю.

**Comment by firefoxic** [comment]
Нормально всё ;)
Главное, чтобы если что-то набрано — зря не пропало вместе с потраченным временем :)
