### ISSUE TITLE
Автоматизировать генерацию текста для SoundCloud

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast-old#93]
Сейчас описание выпуска пишется в MD и живёт на Гитхабе, но SoundCloud поддерживает в описании только _plain text_ и каждый раз приходится делать такое:

```
[Слушайте на SoundCloud](https://soundcloud.com/web-standards/episode-N), [обсуждайте в Слаке](https://web-standards.slack.com/messages/podcast/).

## 00:00 Тема 1

- [Статья](ссылка)
- [Статья](ссылка)

---

Слушайте на SoundCloud — https://soundcloud.com/web-standards/episode-N
Обсуждайте в Слаке — https://web-standards.slack.com/messages/podcast/

00:00 Тема 1

Статья — ссылка
Статья — ссылка
```

Как бы это хорошо автоматизировать? Набор регекспов или как-то ещё. Иначе уходит много времени и постоянно какие-то ошибки всплывают.

**Comment by firefoxic** [comment]
Форму бы какую-то сварганить. Вбиваешь в поля исходные данные, жмакаешь на сабмит, и вылетает два куска текста: один для md, второй для sc. А md можно вообще сразу файлом.

Так можно сразу прикрутить ссылки по таймингу, благо подстановка там наипростейшая.

**Comment by firefoxic** [comment]
А можно всё проще. В Atom есть Markdown Preview. Делаешь всё как надо в md, сохраняешь, по новому файлу (в списке файлов) пкм, там Markdown Preview, в открывшемся превьюхе копируешь текст для SoundCloud.

**Comment by firefoxic** [comment]
Но вариант с формой мне больше нравится. Чего мы, не разрабы чтоли? ;)

**Comment by pepelsbey** [comment]
Форма подразумевает какой-то промежуточный формат, а тут MD как раз самый оптимальный — в нём удобнее всего писать. Нужно поковырять какие-нибудь процессоры MD и приделать к ним свои правила, что ли.

**Comment by firefoxic** [comment]
А вариант с превью в атоме не подходит?

**Comment by Jazzis18** [comment]
Думал какой-нить markdown парсер на питоне сделать. А можно всё также markdown, потом полученный html парсить и по-своему как-то изменять. Структура там минимальная ж выходит.

**Comment by h4** [comment]
Я тут в веточке [uploadMetaToSoundCloud](https://github.com/web-standards-ru/podcast/tree/uploadMetaToSoundCloud) запилил пример того, как можно грузить description на саундклауд.

Что мне не очень нравится, так это то, что авторизация по почте и паролю, такое уж апи у SQ. Писать загрузчик на питоне мне кажется не совсем правильно в этом репозитории.

Ну и пруф того, что всё грузится: https://soundcloud.com/user-859739632/testbadoom

**Comment by Jazzis18** [comment]
@h4 Да, питон тут не к месту, а вот JS.

Я думаю, что надо хотя бы просто тулзу, которая никуда не коннектится, просто на вход markdown, на выходе отформатированный текст. Грузить на саундклауд -- это уже плюшка, главное форматирование сделать, имхо.

Круть)

**Comment by h4** [comment]
@Jazzis18 инструмент для конвертации уже сделан и вмержен в #102

**Comment by pepelsbey** [comment]
Генерация давно автоматизирована, всем спасибо :)
