### ISSUE TITLE
Выпуск №29 — 26:09 Хорошая книга по CSS

### ISSUE THREAD

**Issue by firefoxic** [web-standards/podcast-old#97]
[Аудио](https://soundcloud.com/web-standards/episode-29). [Текст](https://github.com/web-standards-ru/podcast/blob/master/episodes/episode-29.md).

Берётесь расшифровать — отпишитесь здесь об этом.

Не забудьте ознакомиться с [CONTRIBUTING.md](https://github.com/web-standards-ru/podcast/blob/master/CONTRIBUTING.md).

**Comment by Jazzis18** [comment]
Беру.
